# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Lite
version:      0.002_01
version_from: lib/Class/DBI/Lite.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0
    DBD::SQLite:                   0
    DBI:                           0
    DBIx::ContextualFetch:         0
    SQL::Abstract:                 0
    SQL::Abstract::Limit:          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
